monolog:
    handlers:
        app:
            type: service
            id: SchulIT\CommonBundle\Monolog\DatabaseHandler
            level: info
            channels: ["!request", "!php"]
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
